#!/bin/bash
pyfile="$PYFILE"
echo "Compiling $pyfile ..."
python3 -m compileall -b "$pyfile" >/dev/null 2>&1
if [ $? -eq 0 ]; then
echo "$pyfile compiled successfully!"
else
echo "Compilation failed."
fi
